"""QCE agent router — load, train, infer."""

from router.config import (
    AGENTS,
    PROBA_COLS,
    PRODUCTION_FEATURE_SET,
    PRODUCTION_ROUTER_PATH,
    ROUTER_MODEL_PATH,
    TARGET,
    resolve_dataset_name,
)
from router.router import (
    RuntimeRouter,
    attach_router_predictions,
    build_eval_features,
    ensure_eval_features,
    evaluate,
    load_eval_parquet,
    load_router,
    load_router_frame,
    load_split,
    load_split_for_feature_set,
    normalize_feature_set,
    router_feature_cols,
    run_agent_cascade,
    save_router,
    top_k_from_row,
    train_router,
    validate_feature_set_data,
)

__all__ = [
    "AGENTS",
    "PROBA_COLS",
    "PRODUCTION_FEATURE_SET",
    "PRODUCTION_ROUTER_PATH",
    "ROUTER_MODEL_PATH",
    "TARGET",
    "RuntimeRouter",
    "attach_router_predictions",
    "build_eval_features",
    "ensure_eval_features",
    "evaluate",
    "load_eval_parquet",
    "load_router",
    "load_router_frame",
    "load_split",
    "load_split_for_feature_set",
    "normalize_feature_set",
    "resolve_dataset_name",
    "router_feature_cols",
    "run_agent_cascade",
    "save_router",
    "top_k_from_row",
    "train_router",
    "validate_feature_set_data",
]
