"""QCE router: train, evaluate, predict, and paper analysis."""

from routing.analysis import run_full_analysis
from routing.config import (
    LEGACY_HARD_HGBM_PATH,
    PRIMARY_ROUTER_PATH,
    PRODUCTION_FEATURE_SET,
    PRODUCTION_HGBM_PARAMS,
    PRODUCTION_ROUTER_PATH,
    SECONDARY_ROUTER_PATH,
    TUNED_HGBM_PARAMS,
    TUNED_ROUTER_PATH,
)
from routing.router import (
    AGENTS,
    PROBA_COLS,
    ROUTER_MODEL_PATH,
    RuntimeRouter,
    attach_router_predictions,
    build_eval_features,
    ensure_eval_features,
    evaluate,
    load_eval_parquet,
    load_router,
    load_router_frame,
    load_split,
    normalize_feature_set,
    predict_agent_proba,
    resolve_dataset_name,
    router_feature_cols,
    run_agent_cascade,
    top_k_from_row,
    save_router,
    train_router,
    validate_feature_set_data,
)

__all__ = [
    "AGENTS",
    "PROBA_COLS",
    "LEGACY_HARD_HGBM_PATH",
    "PRIMARY_ROUTER_PATH",
    "PRODUCTION_FEATURE_SET",
    "PRODUCTION_HGBM_PARAMS",
    "PRODUCTION_ROUTER_PATH",
    "ROUTER_MODEL_PATH",
    "SECONDARY_ROUTER_PATH",
    "TUNED_HGBM_PARAMS",
    "TUNED_ROUTER_PATH",
    "RuntimeRouter",
    "attach_router_predictions",
    "build_eval_features",
    "ensure_eval_features",
    "evaluate",
    "load_eval_parquet",
    "load_router",
    "load_router_frame",
    "load_split",
    "normalize_feature_set",
    "predict_agent_proba",
    "resolve_dataset_name",
    "router_feature_cols",
    "run_agent_cascade",
    "top_k_from_row",
    "run_full_analysis",
    "save_router",
    "train_router",
    "validate_feature_set_data",
]
