"""
Router configuration — paths, feature sets, and HGBM variants.

Domain modules::

    config.local.router.paths      — split CSVs, feature parquet paths
    config.local.router.labels     — TARGET, AGENTS, PROBA_COLS
    config.local.router.production — deploy defaults (primary/secondary routers)
    config.local.router.legacy     — archived experiment ids
    config.local.router.features   — feature-set specs and normalization
    config.local.router.ablations  — paper ablation cases
    config.local.router.tuning     — HGBM search grid

Shared domain constants live in ``config.local.constants`` (datasets, heuristics, models).
"""

from __future__ import annotations

from config.common import REPO_ROOT
from config.local.constants.datasets import (
    DATASET_DISPLAY,
    DATASET_DISPLAY_NAMES,
    DISCUSSION_DATASET_ORDER,
    resolve_dataset_name,
)
from config.local.constants.heuristics import (
    HEUR_DIMENSION_KEYS,
    HEUR_ROUTER_ATOMIC_COLS,
    HEUR_ROUTER_COLS,
    HEUR_ROUTER_DIM_COLS,
    HEUR_ROUTER_TD_COLS,
    PLANNER_TOOL_NAMES,
)
from config.local.constants.models import DEFAULT_AGENT_MODEL
from config.local.router.ablations import (
    AblationCase,
    CVEC5_ABLATION_CASES,
    TRUST_ABLATION_CASES,
)
from config.local.router.features import (
    CANONICAL_FEATURE_SETS,
    CVEC5_FEATURE_SETS,
    EXPERIMENT_ID_BY_FEATURE_SET,
    FEATURE_SET_ALIASES,
    FEATURE_SET_CLI_CHOICES,
    FEATURE_SET_SPECS,
    FeatureSet,
    FeatureSetSpec,
    TRUST_FEATURE_SETS,
    experiment_id_for_feature_set,
    feature_set_cvec_version,
    feature_set_needs_embeddings,
    feature_set_needs_heuristics,
    feature_set_spec,
    is_production_feature_set,
    model_dir_for_feature_set,
    model_path_for_feature_set,
    normalize_feature_set,
)
from config.local.router.labels import AGENTS, PROBA_COLS, SOFT_DOMINANT, TARGET
from config.local.router.legacy import (
    GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID,
    GRAPH_MAIN_DIM_EMB_MODEL_PATH,
    GRAPH_MAIN_EXPERIMENT_ID,
    GRAPH_MAIN_MODEL_PATH,
    LEGACY_GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID,
    LEGACY_GRAPH_MAIN_EXPERIMENT_ID,
    LEGACY_ROUTER_EXPERIMENT_ID,
    LEGACY_ROUTER_V2_EXPERIMENT_ID,
    LEGACY_TUNED_EXPERIMENT_ID,
    ROUTER_EXPERIMENT_ID,
    ROUTER_V2_EXPERIMENT_ID,
    TUNED_EXPERIMENT_ID,
    TUNED_MODEL_PATH,
)
from config.local.router.paths import (
    BENCHMARK_OUT_ROOT,
    DATASET_ALIASES,
    DECOMPOSER_CACHE_DIR,
    EMBEDDINGS_PARQUET,
    EMBEDDING_COL_PREFIX,
    EVAL_SAMPLES_DIR,
    HEURISTICS_PARQUET,
    HEUR_CALIBRATOR_PATH,
    HEURISTIC_COL_PREFIX,
    LIVE_EVAL_BASELINE_ROOT,
    PCA_PATH,
    QCE_DATASETS,
    QCE_FEATURES_DIR,
    ROUTES_DIR,
    SEED_STABILITY_DIR,
    SOFT_KL_ABLATION_DIR,
    SPLIT_CSV,
    SPLIT_PARQUET,
    TRAIN_NORM_JSON,
    TUNE_OUT_DIR,
)
from config.local.router.production import (
    DEFAULT_HGBM_PARAMS,
    DEFAULT_SELECTIVE_TAU,
    LEGACY_HARD_HGBM_EXPERIMENT_ID,
    LEGACY_HARD_HGBM_PATH,
    PRIMARY_CLASSIFIER,
    PRIMARY_ROUTER_EXPERIMENT_ID,
    PRIMARY_ROUTER_PATH,
    PRODUCTION_CLASSIFIER,
    PRODUCTION_FEATURE_SET,
    PRODUCTION_HGBM_PARAMS,
    PRODUCTION_ROUTER_EXPERIMENT_ID,
    PRODUCTION_ROUTER_PATH,
    PRODUCTION_SUPERVISION,
    REFERENCE_SOFT_HGBM_EXPERIMENT_ID,
    REFERENCE_SOFT_HGBM_PATH,
    REFERENCE_SOFT_LOGREG_EXPERIMENT_ID,
    REFERENCE_SOFT_LOGREG_PATH,
    ROUTER_MODEL_PATH,
    ROUTER_ROLE_BY_CLASSIFIER,
    SECONDARY_CLASSIFIER,
    SECONDARY_ROUTER_EXPERIMENT_ID,
    SECONDARY_ROUTER_PATH,
    SELECTIVE_CHEAP_ROUTER_PATH,
    SELECTIVE_DECOMPOSE_COST_USD,
    SELECTIVE_FULL_ROUTER_PATH,
    SELECTIVE_QCE_OUT_DIR,
    SELECTIVE_TAU_GRID,
    SELECTIVE_TAU_JSON,
    SOFT_KL_SEED_STABILITY_DIR,
    TUNED_HGBM_PARAMS,
    TUNED_ROUTER_EXPERIMENT_ID,
    TUNED_ROUTER_PATH,
    soft_kl_experiment_id,
    soft_kl_out_dir,
)
from config.local.router.tuning import HGBM_GRID

__all__ = [
    "AGENTS",
    "AblationCase",
    "BENCHMARK_OUT_ROOT",
    "CANONICAL_FEATURE_SETS",
    "CVEC5_ABLATION_CASES",
    "CVEC5_FEATURE_SETS",
    "DATASET_ALIASES",
    "DATASET_DISPLAY",
    "DATASET_DISPLAY_NAMES",
    "DECOMPOSER_CACHE_DIR",
    "DEFAULT_AGENT_MODEL",
    "DEFAULT_HGBM_PARAMS",
    "DEFAULT_SELECTIVE_TAU",
    "DISCUSSION_DATASET_ORDER",
    "EMBEDDINGS_PARQUET",
    "EMBEDDING_COL_PREFIX",
    "EVAL_SAMPLES_DIR",
    "EXPERIMENT_ID_BY_FEATURE_SET",
    "FEATURE_SET_ALIASES",
    "FEATURE_SET_CLI_CHOICES",
    "FEATURE_SET_SPECS",
    "FeatureSet",
    "FeatureSetSpec",
    "GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID",
    "GRAPH_MAIN_DIM_EMB_MODEL_PATH",
    "GRAPH_MAIN_EXPERIMENT_ID",
    "GRAPH_MAIN_MODEL_PATH",
    "HEURISTICS_PARQUET",
    "HEUR_CALIBRATOR_PATH",
    "HEUR_DIMENSION_KEYS",
    "HEURISTIC_COL_PREFIX",
    "HEUR_ROUTER_ATOMIC_COLS",
    "HEUR_ROUTER_COLS",
    "HEUR_ROUTER_DIM_COLS",
    "HEUR_ROUTER_TD_COLS",
    "HGBM_GRID",
    "LEGACY_GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID",
    "LEGACY_GRAPH_MAIN_EXPERIMENT_ID",
    "LEGACY_HARD_HGBM_EXPERIMENT_ID",
    "LEGACY_HARD_HGBM_PATH",
    "LEGACY_ROUTER_EXPERIMENT_ID",
    "LEGACY_ROUTER_V2_EXPERIMENT_ID",
    "LEGACY_TUNED_EXPERIMENT_ID",
    "LIVE_EVAL_BASELINE_ROOT",
    "PCA_PATH",
    "PLANNER_TOOL_NAMES",
    "PRIMARY_CLASSIFIER",
    "PRIMARY_ROUTER_EXPERIMENT_ID",
    "PRIMARY_ROUTER_PATH",
    "PROBA_COLS",
    "PRODUCTION_CLASSIFIER",
    "PRODUCTION_FEATURE_SET",
    "PRODUCTION_HGBM_PARAMS",
    "PRODUCTION_ROUTER_EXPERIMENT_ID",
    "PRODUCTION_ROUTER_PATH",
    "PRODUCTION_SUPERVISION",
    "QCE_DATASETS",
    "QCE_FEATURES_DIR",
    "REFERENCE_SOFT_HGBM_EXPERIMENT_ID",
    "REFERENCE_SOFT_HGBM_PATH",
    "REFERENCE_SOFT_LOGREG_EXPERIMENT_ID",
    "REFERENCE_SOFT_LOGREG_PATH",
    "REPO_ROOT",
    "ROUTER_EXPERIMENT_ID",
    "ROUTER_MODEL_PATH",
    "ROUTER_ROLE_BY_CLASSIFIER",
    "ROUTER_V2_EXPERIMENT_ID",
    "ROUTES_DIR",
    "SECONDARY_CLASSIFIER",
    "SECONDARY_ROUTER_EXPERIMENT_ID",
    "SECONDARY_ROUTER_PATH",
    "SEED_STABILITY_DIR",
    "SELECTIVE_CHEAP_ROUTER_PATH",
    "SELECTIVE_DECOMPOSE_COST_USD",
    "SELECTIVE_FULL_ROUTER_PATH",
    "SELECTIVE_QCE_OUT_DIR",
    "SELECTIVE_TAU_GRID",
    "SELECTIVE_TAU_JSON",
    "SOFT_DOMINANT",
    "SOFT_KL_ABLATION_DIR",
    "SOFT_KL_SEED_STABILITY_DIR",
    "SPLIT_CSV",
    "SPLIT_PARQUET",
    "TARGET",
    "TRAIN_NORM_JSON",
    "TRUST_ABLATION_CASES",
    "TRUST_FEATURE_SETS",
    "TUNED_EXPERIMENT_ID",
    "TUNED_HGBM_PARAMS",
    "TUNED_MODEL_PATH",
    "TUNED_ROUTER_EXPERIMENT_ID",
    "TUNED_ROUTER_PATH",
    "TUNE_OUT_DIR",
    "experiment_id_for_feature_set",
    "feature_set_cvec_version",
    "feature_set_needs_embeddings",
    "feature_set_needs_heuristics",
    "feature_set_spec",
    "is_production_feature_set",
    "model_dir_for_feature_set",
    "model_path_for_feature_set",
    "normalize_feature_set",
    "resolve_dataset_name",
    "soft_kl_experiment_id",
    "soft_kl_out_dir",
]
