"""Legacy router experiment ids and archived model paths."""

from __future__ import annotations

from config.local.router.paths import _ROUTER_MODELS, _joblib
from config.local.router.production import LEGACY_HARD_HGBM_PATH

LEGACY_ROUTER_EXPERIMENT_ID = "hgbm_graph_emb_balanced"
LEGACY_GRAPH_MAIN_EXPERIMENT_ID = "hgbm_graph_main_balanced"
LEGACY_GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID = "hgbm_graph_main_dim_emb_balanced"
LEGACY_ROUTER_V2_EXPERIMENT_ID = "hgbm_graph_emb_v2_balanced"
LEGACY_TUNED_EXPERIMENT_ID = "hgbm_graph_emb_tuned"

ROUTER_EXPERIMENT_ID = LEGACY_ROUTER_EXPERIMENT_ID
GRAPH_MAIN_EXPERIMENT_ID = LEGACY_GRAPH_MAIN_EXPERIMENT_ID
GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID = LEGACY_GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID
ROUTER_V2_EXPERIMENT_ID = LEGACY_ROUTER_V2_EXPERIMENT_ID
TUNED_EXPERIMENT_ID = LEGACY_TUNED_EXPERIMENT_ID
GRAPH_MAIN_MODEL_PATH = _joblib(LEGACY_GRAPH_MAIN_EXPERIMENT_ID)
GRAPH_MAIN_DIM_EMB_MODEL_PATH = LEGACY_HARD_HGBM_PATH
TUNED_MODEL_PATH = _joblib(LEGACY_TUNED_EXPERIMENT_ID, root=_ROUTER_MODELS)

__all__ = [
    "GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID",
    "GRAPH_MAIN_DIM_EMB_MODEL_PATH",
    "GRAPH_MAIN_EXPERIMENT_ID",
    "GRAPH_MAIN_MODEL_PATH",
    "LEGACY_GRAPH_MAIN_DIM_EMB_EXPERIMENT_ID",
    "LEGACY_GRAPH_MAIN_EXPERIMENT_ID",
    "LEGACY_ROUTER_EXPERIMENT_ID",
    "LEGACY_ROUTER_V2_EXPERIMENT_ID",
    "LEGACY_TUNED_EXPERIMENT_ID",
    "ROUTER_EXPERIMENT_ID",
    "ROUTER_V2_EXPERIMENT_ID",
    "TUNED_EXPERIMENT_ID",
    "TUNED_MODEL_PATH",
]
